export let stocks = [
  {
    stock: "APPL",
    companyName: "Apple Company",
    industry: "Technology",
    qty: 10,
    price: 100,
  },
  {
    stock: "GOOG",
    companyName: "Google Company",
    industry: "Technology",
    qty: 50,
    price: 1010,
  },
  {
    stock: "WBA",
    companyName: "Walgreen",
    industry: "Pharmacy",
    qty: 50,
    price: 30,
  },
  {
    stock: "FB",
    companyName: "Facebook Company",
    industry: "Technology",
    qty: 100,
    price: 140,
  },
  {
    stock: "XOM",
    companyName: "Exxon Mobile",
    industry: "Oil",
    qty: 20,
    price: 80,
  },
  {
    stock: "VAPPL",
    companyName: "Apple Company",
    industry: "Technology",
    qty: 10,
    price: 100,
  },
  {
    stock: "AGOOG",
    companyName: "Google Company",
    industry: "Technology",
    qty: 50,
    price: 1010,
  },
  {
    stock: "AWBA",
    companyName: "Walgreen",
    industry: "Pharmacy",
    qty: 50,
    price: 30,
  },
  {
    stock: "AFB",
    companyName: "Facebook Company",
    industry: "Technology",
    qty: 100,
    price: 140,
  },
  {
    stock: "AOM",
    companyName: "Exxon Mobile",
    industry: "Oil",
    qty: 20,
    price: 80,
  },
  {
    stock: "YAPPL",
    companyName: "Apple Company",
    industry: "Technology",
    qty: 10,
    price: 100,
  },
  {
    stock: "YGOOG",
    companyName: "Google Company",
    industry: "Technology",
    qty: 50,
    price: 1010,
  },
  {
    stock: "YWBA",
    companyName: "Walgreen",
    industry: "Pharmacy",
    qty: 50,
    price: 30,
  },
  {
    stock: "YFB",
    companyName: "Facebook Company",
    industry: "Technology",
    qty: 100,
    price: 140,
  },
  {
    stock: "YXOM",
    companyName: "Exxon Mobile",
    industry: "Oil",
    qty: 20,
    price: 80,
  },
];
